### ISSUE TITLE
script tags are stripped 

### ISSUE THREAD

**Issue by andy-io** [romanvm/django-tinymce4-lite#8] opened 2017-05-11 06:20 UTC
Hi, when i insert a script tag inside the tiny mce editor in django admin, the script tags are stripped. i tried the following setting but doesnt work.
`TINYMCE_DEFAULT_CONFIG = {
    'selector': 'textarea',
    'theme': 'modern',
    'plugins': 'link image preview codesample contextmenu table code',
    'toolbar1': 'bold italic underline | alignleft aligncenter alignright alignjustify '
                '| bullist numlist | outdent indent | table | link image | codesample | preview code',
    'contextmenu': 'formats | link image',
    'menubar': False,
    'inline': False,
    'statusbar': True,
    'height': 360,
    'schema': 'html5',
    'allow_script_urls': True,
    'extended_valid_elements': 'script[charset|defer|async|language|src|type],iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder],',
}`

**Comment by romanvm** [comment] 2017-05-11 08:02
Please described your issue in more detail. When are `script` tags stripped? When you add them via TinyMCE code editor or when your text is saved? Anyway, I cannot reproduce your issue. I have added `'allow_script_urls': True, 'extended_valid_elements': 'script[charset|defer|async|language|src|type]'` and inserted a simple JS alert box via TinyMCE code editor (`<>` button) and it wasn't stripped. It does not work in the editor, of course, but it works on the final pages. 

Anyway, if the issue with the TinyMCE editor itself, it should be addressed to TinyMCE support team. I can help with TinyMCE<>Django integration part (within my abilities), but I'm no expert in TinyMCE core functionality.

**Comment by andy-io** [comment] 2017-05-11 11:24
if i add the script by clicking the source code `<>` button as you said , then it works but if i add via the editor then it doesn't work.

**Comment by romanvm** [comment] 2017-05-11 11:36
It shouldn't work via the editor. This is what a WYSIWYG editor is about: you don't work with raw tags but see the content as it appears on a website and you certainly cannot see `script` tags without looking into html source. If you need to insert samples of code that should be visible to readers, use `codesample` plugin, otherwise choose a different method to insert scripts into your content.

I'm closing this issue because it is certainly not relevant to `django-tinymce4-lite` package.

**Closed as completed by romanvm** 2017-05-11 11:36 UTC
